[project]
name = "testcrew_ai"
version = "0.1.0"
description = "testcrew-ai using crewAI"
authors = [{ name = "Your Name", email = "you@example.com" }]
requires-python = ">=3.10,<3.14"
dependencies = [
    "crewai[tools]==1.10.1"
]

[project.scripts]
testcrew_ai = "testcrew_ai.main:run"
run_crew = "testcrew_ai.main:run"
train = "testcrew_ai.main:train"
replay = "testcrew_ai.main:replay"
test = "testcrew_ai.main:test"
run_with_trigger = "testcrew_ai.main:run_with_trigger"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.crewai]
type = "crew"
